version: '3'
services:
  web:
    build: .
    env_file:
      - .env
    ports:
      - '80:4000'
  postgres:
    image: mdillon/postgis
    volumes:
      - './data/postgres:/var/lib/postgresql/data'
    env_file:
      - .env
    ports:
      - '5432:5432'
  redis:
    image: redis
    volumes:
      - './data/redis:/data'
    env_file:
      - .env
    ports:
      - '6379:6379'
  prometheus:
    image: prom/prometheus
    user: 'root'
    volumes: 
      - './prometheus.yml:/etc/prometheus/prometheus.yml'
      - './data/prometheus:/prometheus'
    env_file:
      - .env
    ports:
      - '9090:9090'
