version: '3'
services:
  postgres:
    image: mdillon/postgis
    env_file:
      - .env
    ports:
      - '5432:5432'
  redis:
    image: redis
    env_file:
      - .env
    ports:
      - '6379:6379'
  prometheus:
    image: prom/prometheus
    volumes: 
      - './prometheus.yml:/etc/prometheus/prometheus.yml'
    env_file:
      - .env
    ports:
      - '9090:9090'
  pushgateway:
    image: prom/pushgateway
    env_file:
      - .env
    ports:
      - '9091:9091'
